// apps/demo/src/react-page/App.tsx
import { useCallback, useRef, useState } from 'react'
import type { ChangeEvent } from 'react'
import { BidirectionalTree } from '@d3-tree/react'
import type { BidirectionalTreeHandle, TreeNodeData } from '@d3-tree/react'
import { industryData } from '../data'

type PickMode = 'none' | 'add' | 'remove'

const DEFAULT_HINT = '点击节点可折叠/展开；滚轮缩放、拖拽平移'

export default function App() {
  const tree = useRef<BidirectionalTreeHandle | null>(null)
  const seq = useRef(0)

  const [mode, setMode] = useState<PickMode>('none')
  const [picked, setPicked] = useState<TreeNodeData | null>(null)
  const [newName, setNewName] = useState('')
  const [hint, setHint] = useState(DEFAULT_HINT)
  const [searchKw, setSearchKw] = useState('')
  const [groups, setGroups] = useState<Array<{ name: string; color: string }>>([])
  const [activeGroups, setActiveGroups] = useState<Set<string>>(new Set())

  const enterMode = useCallback((next: PickMode) => {
    setMode(next)
    setPicked(null)
    tree.current?.setToggleOnNodeClick(next === 'none')
    setHint(next === 'none' ? DEFAULT_HINT : '选取模式：请点击目标节点')
  }, [])

  const onNodeSelect = useCallback(
    (node: TreeNodeData) => {
      if (mode === 'none') return
      setPicked(node)
      setHint(
        mode === 'add'
          ? `已选父节点「${node.name}」，输入名称后确认`
          : `已选节点「${node.name}」，再次点击“删除节点”确认删除`,
      )
    },
    [mode],
  )

  const confirmAdd = useCallback(() => {
    const name = newName.trim()
    if (!picked || !name) {
      setHint('请先选取父节点并输入名称')
      return
    }
    const ok = tree.current?.addChild(picked.id, {
      id: `custom-${Date.now()}-${seq.current++}`,
      name,
    })
    setHint(ok ? `已在「${picked.name}」下追加「${name}」` : '追加失败：父节点不存在')
    setNewName('')
    enterMode('none')
  }, [newName, picked, enterMode])

  const onRemove = useCallback(() => {
    if (mode === 'remove' && picked) {
      const ok = tree.current?.removeChild(picked.id)
      setHint(ok ? `已删除「${picked.name}」` : '该节点不可删除（根节点）')
      enterMode('none')
      return
    }
    enterMode('remove')
  }, [mode, picked, enterMode])

  const onSearch = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    const kw = e.target.value.trim()
    setSearchKw(e.target.value)
    if (!kw) {
      tree.current?.clearSearch()
      setHint(DEFAULT_HINT)
      return
    }
    const hits = tree.current?.search(kw) ?? 0
    setHint(hits > 0 ? `「${kw}」命中 ${hits} 个节点` : `「${kw}」无命中`)
  }, [])

  const onGroupsChange = useCallback((gs: Array<{ name: string; color: string }>) => {
    setGroups(gs)
    setActiveGroups(new Set(gs.map(g => g.name)))
  }, [])

  const toggleGroup = useCallback((name: string) => {
    setActiveGroups(prev => {
      const next = new Set(prev)
      if (next.has(name)) next.delete(name)
      else next.add(name)
      tree.current?.setVisibleGroups(next.size ? [...next] : null)
      return next
    })
  }, [])

  return (
    <>
      <header>
        <h1>双向树图谱 · React 组件</h1>
        <nav>
          <a href="/index.html">示例中心</a>
          <a href="/vue.html">Vue</a>
          <a href="/react.html" className="active" aria-current="page">
            React
          </a>
        </nav>
      </header>
      <div id="toolbar">
        <div className="tb-group" role="group" aria-label="编辑">
          <span className="tb-label">编辑</span>
          <div className="tb-controls">
            <button onClick={() => enterMode('add')}>追加子节点</button>
            <button disabled={mode === 'add'} onClick={onRemove}>
              删除节点
            </button>
            {mode === 'add' && (
              <>
                <input
                  value={newName}
                  placeholder="新节点名称"
                  aria-label="新节点名称"
                  onChange={e => setNewName(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && confirmAdd()}
                />
                <button className="primary" onClick={confirmAdd}>
                  确认追加
                </button>
              </>
            )}
            {mode !== 'none' && <button onClick={() => enterMode('none')}>取消</button>}
          </div>
        </div>
        <span className="divider" />
        <div className="tb-group" role="group" aria-label="搜索">
          <span className="tb-label">搜索</span>
          <div className="tb-controls">
            <input value={searchKw} placeholder="关键词…" aria-label="搜索节点" onChange={onSearch} />
          </div>
        </div>
        <span className="divider" />
        <div className="tb-group" role="group" aria-label="导出">
          <span className="tb-label">导出</span>
          <div className="tb-controls">
            <button
              onClick={() => tree.current?.exportImage({ format: 'svg', filename: '产业链图谱-React' })}
            >
              SVG
            </button>
            <button
              onClick={() =>
                tree.current?.exportImage({ format: 'png', scale: 2, filename: '产业链图谱-React' })
              }
            >
              PNG
            </button>
          </div>
        </div>
        <span className="divider" />
        <div className="tb-group" role="group" aria-label="视图">
          <span className="tb-label">视图</span>
          <div className="tb-controls">
            <button
              onClick={() => {
                tree.current?.expandAll()
                tree.current?.zoomToFit()
              }}
            >
              全展开
            </button>
            <button
              onClick={() => {
                tree.current?.collapseAll()
                tree.current?.zoomToFit()
              }}
            >
              全收起
            </button>
            <button onClick={() => tree.current?.zoomToFit()}>适配视窗</button>
          </div>
        </div>
        <span id="hint" className={mode !== 'none' ? 'active' : undefined}>
          {hint}
        </span>
        <div id="legend" aria-label="分组图例">
          {groups.map(g => (
            <span
              key={g.name}
              className={`chip${activeGroups.has(g.name) ? '' : ' off'}`}
              onClick={() => toggleGroup(g.name)}
            >
              <span className="dot" style={{ background: g.color }} />
              {g.name}
            </span>
          ))}
        </div>
      </div>
      <div id="chart">
        <BidirectionalTree
          ref={tree}
          data={industryData}
          colorByGroup
          onNodeSelect={onNodeSelect}
          onGroupsChange={onGroupsChange}
        />
      </div>
    </>
  )
}

// apps/demo/src/vue-page/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { BidirectionalTree } from '@d3-tree/vue'
import type { BidirectionalTreeExposed, TreeNodeData } from '@d3-tree/vue'
import { industryData } from '../data'

const tree = ref<BidirectionalTreeExposed | null>(null)

type PickMode = 'none' | 'add' | 'remove'
const mode = ref<PickMode>('none')
const pickedName = ref('')
const pickedId = ref<string | null>(null)
const newName = ref('')
const hint = ref('点击节点可折叠/展开；滚轮缩放、拖拽平移')
const defaultHint = '点击节点可折叠/展开；滚轮缩放、拖拽平移'
const searchKw = ref('')
const groups = ref<Array<{ name: string; color: string }>>([])
const activeGroups = ref(new Set<string>())
let seq = 0

function setMode(next: PickMode): void {
  mode.value = next
  pickedId.value = null
  tree.value?.setToggleOnNodeClick(next === 'none')
  if (next === 'none') hint.value = defaultHint
  else hint.value = '选取模式：请点击目标节点'
}

function onNodeSelect(node: TreeNodeData): void {
  if (mode.value === 'none') return
  pickedId.value = node.id
  pickedName.value = node.name
  if (mode.value === 'add') hint.value = `已选父节点「${node.name}」，输入名称后确认`
  else hint.value = `已选节点「${node.name}」，再次点击“删除节点”确认删除`
}

function confirmAdd(): void {
  const name = newName.value.trim()
  if (!pickedId.value || !name) {
    hint.value = '请先选取父节点并输入名称'
    return
  }
  const ok = tree.value?.addChild(pickedId.value, { id: `custom-${Date.now()}-${seq++}`, name })
  hint.value = ok ? `已在「${pickedName.value}」下追加「${name}」` : '追加失败：父节点不存在'
  newName.value = ''
  setMode('none')
}

function onRemove(): void {
  if (mode.value === 'remove' && pickedId.value) {
    const ok = tree.value?.removeChild(pickedId.value)
    hint.value = ok ? `已删除「${pickedName.value}」` : '该节点不可删除（根节点）'
    setMode('none')
    return
  }
  setMode('remove')
}

function onSearch(): void {
  const kw = searchKw.value.trim()
  if (!kw) {
    tree.value?.clearSearch()
    hint.value = defaultHint
    return
  }
  const hits = tree.value?.search(kw) ?? 0
  hint.value = hits > 0 ? `「${kw}」命中 ${hits} 个节点` : `「${kw}」无命中`
}

function toggleGroup(name: string): void {
  if (activeGroups.value.has(name)) activeGroups.value.delete(name)
  else activeGroups.value.add(name)
  tree.value?.setVisibleGroups(activeGroups.value.size ? [...activeGroups.value] : null)
}

function onGroupsChange(gs: Array<{ name: string; color: string }>): void {
  groups.value = gs
  activeGroups.value = new Set(gs.map(g => g.name))
}
</script>

<template>
  <header>
    <h1>双向树图谱 · Vue 3 组件</h1>
    <nav>
      <a href="/index.html">示例中心</a>
      <a href="/vue.html" class="active" aria-current="page">Vue</a>
      <a href="/react.html">React</a>
    </nav>
  </header>
  <div id="toolbar">
    <div class="tb-group" role="group" aria-label="编辑">
      <span class="tb-label">编辑</span>
      <div class="tb-controls">
        <button @click="setMode('add')">追加子节点</button>
        <button :disabled="mode === 'add'" @click="onRemove">删除节点</button>
        <input v-if="mode === 'add'" v-model="newName" placeholder="新节点名称" aria-label="新节点名称"
          @keydown.enter="confirmAdd" />
        <button v-if="mode === 'add'" class="primary" @click="confirmAdd">确认追加</button>
        <button v-if="mode !== 'none'" @click="setMode('none')">取消</button>
      </div>
    </div>
    <span class="divider"></span>
    <div class="tb-group" role="group" aria-label="搜索">
      <span class="tb-label">搜索</span>
      <div class="tb-controls">
        <input v-model="searchKw" placeholder="关键词…" aria-label="搜索节点" @input="onSearch" />
      </div>
    </div>
    <span class="divider"></span>
    <div class="tb-group" role="group" aria-label="导出">
      <span class="tb-label">导出</span>
      <div class="tb-controls">
        <button @click="tree?.exportImage({ format: 'svg', filename: '产业链图谱-Vue' })">SVG</button>
        <button @click="tree?.exportImage({ format: 'png', scale: 2, filename: '产业链图谱-Vue' })">PNG</button>
      </div>
    </div>
    <span class="divider"></span>
    <div class="tb-group" role="group" aria-label="视图">
      <span class="tb-label">视图</span>
      <div class="tb-controls">
        <button @click="tree?.expandAll(); tree?.zoomToFit()">全展开</button>
        <button @click="tree?.collapseAll(); tree?.zoomToFit()">全收起</button>
        <button @click="tree?.zoomToFit()">适配视窗</button>
      </div>
    </div>
    <span id="hint" :class="{ active: mode !== 'none' }">{{ hint }}</span>
    <div id="legend" aria-label="分组图例">
      <span v-for="g in groups" :key="g.name" class="chip"
        :class="{ off: !activeGroups.has(g.name) }" @click="toggleGroup(g.name)">
        <span class="dot" :style="{ background: g.color }"></span>{{ g.name }}
      </span>
    </div>
  </div>
  <div id="chart">
    <BidirectionalTree ref="tree" :data="industryData" color-by-group
      @node-select="onNodeSelect" @groups-change="onGroupsChange" />
  </div>
</template>

<style>
#app { width: 100vw; height: 100vh; display: flex; flex-direction: column; }
#chart .d3t-host { width: 100%; height: 100%; }
</style>
